version: '3'

tasks:
  default:
    desc: help
    deps:
      - help

  build:
    desc: Build the gem
    cmds:
      - gem build

  release:
    cmds:
      - rake release
    desc: Release a new version of the gem

  test:
    desc: Run tests
    cmds:
      - bundle exec rake test

  lint:
    desc: Run linter
    cmds:
      - bundle exec standardrb

  help:
    desc: list all tasks
    silent: true
    cmds:
      - task --list-all